config/routes.rb
RailsSample::Application.routes.draw do
  resources :slides, :only => [:show]
  resources :action_items, :only => [:create, :update, :destroy]
  resources :users do
    member do
      put :change_password_update
    end
  end
  
  resources :story_boards
  resources :story_boards do
    resources :slides do
      post :resize
      post :crop
    end
    member do
      get :preview
      get :duplicate
    end
  end
  resources :story_board_attachments, :only => [:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_prospects

  root :to => "home#index"
  
  match '/signup',  :to => 'users#new', :as => :sign_up
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/change_password', :to => 'users#change_password', :as => :change_password

  match 'ajax/editable' => 'ajax#editable'
  

end

app/models/story_board.rb
class StoryBoard < ActiveRecord::Base
  include Shared::AttachmentHelper
  include Shared::SlideCreator 
  
  belongs_to :user
  has_many :slides, :order => "order_number", :dependent => :destroy
  has_many :attachments, :foreign_key => 'story_board_id', :class_name => 'StoryBoardAttachment', :dependent => :destroy
  # accepts_nested_attributes_for :attachments, :allow_destroy => true 
  
  validates_presence_of :title
  
  attr_accessor :starting_order_number
  
  before_save   :set_dirty_flag
  after_save    :schedule_worker
  
  DEFAULT_TITLE = 'Untitled'
  DEFAULT_BACKGROUND = 'Web 1024'
  FILE_TYPES_ALLOWED = ['.PDF','.JPG','.PNG','.GIF']
  
  def duplicate
    dup_story_board = StoryBoard.create(:user_id => self.user_id, :title => get_next_duplicate_title, :background => self.background, :duplicating => true)    
    schedule_duplicate(dup_story_board)  
    dup_story_board
  end
  
  def mobile_safari_layout?
    background == "iPad" || background == "iPhone"
  end
  
  def clean?
    !dirty? && !self.duplicating
  end
  
  def private?
    self.security_level == 'private'
  end
  
  def valid_password?(user_entered_password)
    self.password == user_entered_password
  end
  
  def security_level_desc
    {'public' => 'Public on the web', 'link' => 'Anyone with link', 'private' => 'Private'}[self.security_level]
  end
  
  def variables
    variables = []
    slides.each do |slide|
      slide.action_items.each do |action_item|
        if action_item.data_attrs['data_save_variable'].present?
          variables.push(action_item.data_attrs['data_save_variable'])
        end
      end
    end
    return variables
  end
  
  def has_slides?
    slides.count > 0
  end
  
  def get_next_duplicate_title      
    for i in 1..100
      title = "#{self.title} #{i}"
      break if self.user.story_boards.where(:title => title).size == 0
    end 
    title
  end
  
  def attachments_present?
    if slides.size == 0 && attachments.not_processed.size == 0
      errors.add(:attachments, "need to be uploaded before you can save")
      false
    else 
      true
    end
  end
  
  def empty_links_to(deleting_slide)
    story_board_internal_links = self.slides.map(&:internal_link_action_items).reject{|l| l.blank?}.flatten
    action_items_to_update = story_board_internal_links.select{|l| l.data["internal_link"] == "#{deleting_slide.id}"}
    action_items_to_update.map(&:remove_internal_link)
  end
  
  def attachments_attributes=(attributes)
    attributes.each{ |a| self.attachments.create :upload => a }
  end
  
  def json_response
    self.attachments.size > 0 ? self.attachments.map(&:to_fileupload_json) : self
  end
  
  private

    def schedule_duplicate(dup_story_board)  
      Delayed::Job.enqueue(StoryBoardDuplicateJob.new(self.id, dup_story_board.id))
    end
    
    def schedule_worker  
      Delayed::Job.enqueue(StoryBoardJob.new(self.id, @starting_order_number || 0)) if self.dirty?
    end
    
    def set_dirty_flag
      self.dirty = true if attachments.not_processed.size > 0
    end
    
end

app/controllers/story_boards_controller.rb
class StoryBoardsController < ApplicationController
  before_filter :load_object, :except => [:index, :new, :create]
  before_filter :check_permissions, :only => [:show]

  def index
    @story_boards = current_user.story_boards

    respond_to do |format|
      format.html
      format.json { render :json => @story_boards }
    end
  end

  def show
    session[:create_story_board_id] = nil
    if @story_board.clean?
      @selected_slide = params[:slide_id].present? ? @story_board.slides.find(params[:slide_id].to_i) : @story_board.slides.first
    end
      
    respond_to do |format|
      format.html { render :layout => 'story_board' }
      format.json { render :json => @story_board }
      format.js
    end
  end

  def preview
    @selected_slide = params[:current_slide_id].present? ? @story_board.slides.find(params[:current_slide_id]) : @story_board.slides.first
    if @story_board.private?
      preview_private
    else
      render :layout => 'story_board_preview'
    end
  end
  
  def duplicate
    @new_story_board = @story_board.duplicate
    redirect_to story_boards_path
  end

  def new
    create_story_board

    respond_to do |format|
      format.html
      format.json { render :json => @story_board }
    end
  end

  def create
    @story_board.update_attributes(params[:story_board])
    
    respond_to do |format|
      if @story_board.save
        format.html {  
          render :json => @story_board.attachments.map(&:to_fileupload_json).to_json, 
          :content_type => 'text/html',
          :layout => false
        }
        format.json { render :json => @story_board.json_response.to_json }
        
      else
        format.html { render :action => "new" }
        format.json { render :json => @story_board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /story_boards/1
  # PUT /story_boards/1.json
  def update
    @selected_slide = params[:current_slide_id].present? ? @story_board.slides.find(params[:current_slide_id]) : @story_board.slides.first
    @story_board.update_attributes(params[:story_board])
    
    respond_to do |format|
      if @story_board.attachments_present?
        format.html {  
          render :json => @story_board.attachments.map(&:to_fileupload_json).to_json, 
          :content_type => 'text/html',
          :layout => false
        }
        format.json { render :json => @story_board.json_response.to_json }
        format.js
      else
        format.html { render :action => "edit" }
        format.json { render :json => @story_board.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /story_boards/1
  # DELETE /story_boards/1.json
  def destroy
    @story_board.destroy

    respond_to do |format|
      format.html { redirect_to story_boards_url }
      format.json { head :ok }
    end
  end
  
  private 
  
    def load_object
      @story_board = StoryBoard.find(params[:id])
    end
  
    def check_permissions
      if @story_board.user != current_user
        flash[:notice] = 'Not authorized to view story board'
        redirect_to root_url
      end
    end
    
    def preview_private
      case
      when user_entered_password.present? 
        if @story_board.valid_password?(user_entered_password)
          set_password_to_session
          render :layout => 'story_board_preview'
        else
          preview_needs_password
        end
      when password_in_session?
        @story_board.valid_password?(session_password) ? render(:layout => 'story_board_preview') : preview_needs_password
      else
        render 'preview_private', :layout => 'story_board_preview'
      end
    end
    
    def preview_needs_password
      flash[:error] = "Password was incorrect"
      render 'preview_private', :layout => 'story_board_preview'
    end
    
    def user_entered_password
      if params[:story_board].present? 
        pass = params[:story_board][:password] if params[:story_board][:password].present?
      end
      pass || ''
    end
    
    def password_in_session?
      session[:story_board_passwords].nil? ? false : session_password.present?
    end
    
    def session_password
      session[:story_board_passwords][@story_board.id]
    end
    
    def set_password_to_session
      session[:story_board_passwords] = {} if session[:story_board_passwords].nil?
      session[:story_board_passwords] = session[:story_board_passwords].merge({@story_board.id => @story_board.password})
    end
    
    def new_story_board_in_session?
      !session[:create_story_board_id].nil?
    end
    
    def create_story_board
      @story_board = StoryBoard.create(:title => current_user.next_story_board_title, :user => current_user, :background => StoryBoard::DEFAULT_BACKGROUND)
    end
    
    def find_story_board
      @story_board = StoryBoard.find(params[:id])
    end
end

app/helpers/story_boards_helper.rb
module StoryBoardsHelper
  def image_url(action_item)
    action_item.user_gif.present? ? action_item.user_gif.url : ""
  end
  
  def preview_style(story_board,slide)
    case story_board.background
    when 'iPhone'
      width = 320
      height = 460
    when 'iPad'
      width = 1024
      height = 768  
    when 'Web 1024'
      width = slide.image_width > 1024 ? 1024 : slide.image_width
      height = slide.image_height
    when 'Web 1280'
      width = slide.image_width < 1280 ? slide.image_width : 1280
      height = slide.image_height
    end
    "height: #{height}px; width: #{width}px;"
  end
  
  def right_gutter_style(story_board,slide)
    left = visible_canvas_width(story_board) 
    height = visible_canvas_height(story_board,slide) + bottom_gutter_height(visible_canvas_height(story_board,slide),slide)
    width = right_gutter_width(left,slide)
    "left: #{left}px; height: #{height}px; width: #{width}px"
  end
  
  def bottom_gutter_style(story_board,slide)
    top = visible_canvas_height(story_board,slide)
    height = bottom_gutter_height(top,slide)
    width = visible_canvas_width(story_board)
    "top: #{top}px; height: #{height}px; width: #{width}px"
  end
  
  def right_gutter_data(story_board,slide)
    left = visible_canvas_width(story_board) 
    height = visible_canvas_height(story_board,slide) + bottom_gutter_height(visible_canvas_height(story_board,slide),slide)
    width = right_gutter_width(left,slide)
    {left: left, height: height, width: width}
  end
  
  def bottom_gutter_data(story_board,slide)
    top = visible_canvas_height(story_board,slide)
    height = bottom_gutter_height(top,slide)
    width = visible_canvas_width(story_board)
    {top: top, height: height, width: width}
  end
  
  def visible_canvas_width(story_board)
    case story_board.background
    when 'iPhone' then 320
    when 'iPad' then 1024
    when 'Web 1024' then 1024
    when 'Web 1280'then 1280
    else 0
    end
  end

  def visible_canvas_height(story_board,slide)
    case story_board.background
    when 'iPhone' then 460
    when 'iPad' then 768  
    when 'Web 1024' then slide.image_height
    when 'Web 1280' then slide.image_height
    else 0
    end
  end
  
  private
  
    def right_gutter_width(left,slide)
      width = slide.image_width - left
      width > 30 ? width : 30
    end
  
    def bottom_gutter_height(top,slide)
      height = slide.image_height - top
      height > 30 ? height : 30
    end
  
end

app/views/story_boards/_action_selector_form.html.haml
- if @story_board.clean?
  = render 'action_items/checkbox'
  = render 'action_items/gif'
  = render 'action_items/link'
  = render 'action_items/radio'
  = render 'action_items/text'
  = render 'action_items/variable'
- else
  %p Loading...

app/views/story_boards/_attachment.html.haml
.attachment= image_tag(attachment.upload.url(:thumb))

app/views/story_boards/_form.html.haml
- content_for :head do
  = stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/base/jquery-ui.css', :id => 'theme'
  = stylesheet_link_tag 'fileupload-ui'
  
- content_for :scripts do
  = javascript_include_tag "http://blueimp.github.com/JavaScript-Templates/tmpl.min.js"
  = javascript_include_tag "http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js"
  = javascript_include_tag "http://blueimp.github.com/jQuery-Image-Gallery/js/jquery.image-gallery.min.js"
  = javascript_include_tag 'jquery.iframe-transport'
  = javascript_include_tag 'jquery.fileupload'
  = javascript_include_tag 'jquery.fileupload-fp'
  = javascript_include_tag 'jquery.fileupload-ui'
  = javascript_include_tag 'jquery.fileupload-jui'
  = javascript_include_tag 'file_upload'


- if @story_board.errors.any?
  #error_explanation
    %h2= "#{pluralize(@story_board.errors.count, "error")} prohibited this story_board from being saved:"
    %ul
      - @story_board.errors.full_messages.each do |msg|
        %li= msg

%h2 Upload Images
= form_for @story_board, :html => { :class => "upload", :multipart => true }  do |f|
  
  %p Upload images to create your storyboard screens. Tip: you can select multiple image files. Screens will be created from the following file types:
  %ul
    - StoryBoard::FILE_TYPES_ALLOWED.each do |file_ext|
      %li= file_ext
    = link_to 'more...', '#'
  %p Note: each slide or page will be converted to it's own screen with upload.

  .row.fileupload-buttonbar
    .span7
      %span.btn.btn-success.fileinput-button
        %span Add files...
        = file_field_tag 'story_board[attachments_attributes][]', :multiple => true, :accept => 'image/png,image/gif,image/jpeg,application/pdf'
      = submit_tag 'Start upload', :class => "btn btn-primary start"
      = link_to 'Cancel', @story_board, :method => :delete, :class => "btn btn-warning cancel"
    .span5
      .progress.progress-success.progress-striped.active.fade
        .bar{:style => 'width:0%;'}
  
  .fileupload-loading
  %table.table.table-striped{'data-toggle' => "modal-gallery", 'data-target' => "#modal-gallery"}
    %tbody.files
  
  .well

= render 'shared/file_upload_templates'

app/views/story_boards/_sidebar.html.haml
= form_for @story_board, :remote => true, :html => {:id => 'story_board_save_background'} do |f|
  = hidden_field_tag 'current_slide_id'
  .field
    = f.label :background
    = f.select :background, ['iPad','iPhone','Web 1024','Web 1280']

= select_tag :canvas_zoom, options_for_select((20..200).step(20).map{|x| ["#{x}%", x]}, 100)
  
#story-board-slides
  - if @story_board.has_slides? && @story_board.clean?
    = render 'sidebar_slides'

- if @story_board.clean? and @story_board.has_slides?
  #replace_image_dialog.dialog{:title => 'Replace Slide Image'}  
    = render 'slides/edit_form', :story_board => @story_board, :slide => @selected_slide

app/views/story_boards/_slide_menu.html.haml
%ul
  %li#crop Crop
  %li#resize Resize
  %li#transition 
    = link_to 'Timed Transition', '#', :id => 'transition_link'
    = form_for [@story_board, @selected_slide], :html => {:class => 'hidden'} do |f|
      = f.hidden_field :transfer_to_slide_id
      .field
        = f.label :transfer_to_slide_id, 'Transition to slide'
        = link_to 'Select slide', '#', :id => 'transition_slide_selector'
      .field
        = f.label :transfer_wait, 'Seconds to wait before transition'
        = f.text_field :transfer_wait, :size => 10
      .actions
        = submit_tag :done
        = link_to 'Remove', '#', :id => 'remove_transition'

app/views/story_boards/_storyboard_header.html.haml
%span{:id => "StoryBoard_title_#{@story_board.id}", :class => 'title editable'}= @story_board.title
%span{:id => 'security_level'}= link_to @story_board.security_level_desc, '#'

#storyboard-menu
  %span= link_to "File", "javascript:void(0);"
  |
  %span= link_to "Edit", "javascript:void(0);"
  |
  %span= link_to "Help", "javascript:void(0);"
 
#story_board_security_dialog.dialog{:title => 'Privacy Settings'}
  = form_for @story_board, :remote => true do |f|
    = hidden_field 'current_security_level', @story_board.security_level
    %div.save_error
    .field
      = f.radio_button :security_level, "public"
      = label :security_level_public, 'Public on the web'
      %p Anyone on the Internet can find and access.
    .field
      = f.radio_button :security_level, "link"
      = label :security_level_public, 'Anyone with link'
      %p Anyone with the link can access.
    .field.private
      = f.radio_button :security_level, "private"
      = label :security_level_private, 'private'
      %p Only people explicitly granted permission can access.
    .field.password
      = f.label :password
      = f.text_field :password
    .action
      = f.submit "Save"
      = button_to "Cancel", '#', :class => 'cancel'

app/views/story_boards/_top_menu.html.haml
- if @story_board.clean?
  %ul#story_board_menu
    %li
      = form_tag new_story_board_slide_path(@story_board), :id => 'add_slide_form', :method => :get do
        - if @selected_slide.present?
          = hidden_field_tag 'current_slide_id', @selected_slide.id
        = link_to "Add slide"
        = submit_tag 'Add', :class => 'hidden'

    - if @story_board.has_slides?
      %li
        = form_tag preview_story_board_path(@story_board), :id => 'preview_slide_form', :method => :get do
          = hidden_field_tag 'current_slide_id', @selected_slide.id
          = link_to "Preview"
  
    %li
      = link_to 'Share', '#share_url', :id => 'share_link'
      %div#share_url
        .field
          = label_tag 'URL'
          .value= "#{preview_story_board_url(@story_borad)}"

  - if @story_board.has_slides?
    #slide_menu= render 'slide_menu' 
  
- else
  %p Loading...

app/views/story_boards/edit.html.haml
%h1= @story_board.title

= render 'form'

app/views/story_boards/new.html.haml
%h1= @story_board.title

= render 'form'

app/views/story_boards/preview.html.haml
- content_for :head do
  - if @story_board.mobile_safari_layout?
    %meta{'name' => 'apple-mobile-web-app-capable', :content => 'yes'}
    %meta{'name' => 'apple-mobile-web-app-status-bar-style', :content => 'black'}
    %meta{'name' => 'viewport', :content => 'width=device-width'}

#preview{:data => { :slide_id => @selected_slide.id, 
                    :transfer_to_slide_id => @selected_slide.transfer_to_slide_id,
                    :transfer_wait => @selected_slide.transfer_wait }, 
         :style => preview_style(@story_board,@selected_slide) }
         
  = image_tag @selected_slide.image.url(:web), :size => @selected_slide.image_width.to_s() + "x" + @selected_slide.image_height.to_s()
  - @selected_slide.action_items.order_by_top.each_with_index do |action_item,index|
    .action_item{ :data => action_item.data_attrs.merge({"tabindex" => index+1}), :image_url => image_url(action_item) }
  
#preload
  - @story_board.slides.each do |slide|
    - if slide.id != @selected_slide.id
      = image_tag slide.image.url(:web), :size => slide.image_width.to_s() + "x" + slide.image_height.to_s()

app/views/story_boards/preview_private.html.haml
- content_for :head do
  - if @story_board.mobile_safari_layout?
    %meta{'name' => 'apple-mobile-web-app-capable', :content => 'yes'}
    %meta{'name' => 'apple-mobile-web-app-status-bar-style', :content => 'black'}
    %meta{'name' => 'viewport', :content => 'width=device-width'}

#preview_private
  %h2= @story_board.title
  
  %h3 Please enter password to view.
  = form_tag preview_story_board_path(@story_board), :id => 'preview_slide_form', :method => :get do
    = hidden_field_tag 'current_slide_id', @selected_slide.id
    = label_tag "story_board[password]", 'Password'
    = password_field_tag "story_board[password]"
    = submit_tag "View"

app/views/story_boards/show.html.haml
/ - content_for :head do
/   = stylesheet_link_tag "plupload.queue"
/   = javascript_include_tag "plupload/plupload.full", "plupload/plupload.queue"
/   #uploader_script
/     = javascript_tag do
/       = render "shared/plupload.js"

- content_for :top_menu do
  = render 'top_menu'

- content_for :left_sidebar do
  = render 'sidebar'

- content_for :main do
  #selected-slide= render 'canvas'
  #action-selector-form
    - if @story_board.has_slides?
      = render 'action_selector_form'

app/views/story_boards/show.js.erb
<% if @story_board.clean? %> 
  $('#replace_image_dial og').html("<%= escape_javascript render(:partial => "slides/edit_form", :locals => {:story_board => @story_board, :slide => @selected_slide}) %>");
  $('#selected-slide').html("<%= escape_javascript render(:partial => "canvas") %>");
  $('#action-selector-form').html("<%= escape_javascript render(:partial => "action_selector_form") %>");
  $('#top_menu').html("<%= escape_javascript render(:partial => "top_menu") %>");
  $('#story-board-slides').html("<%= escape_javascript render(:partial => "sidebar_slides") %>");
  $('#selected-slide').html("<%= escape_javascript render(:partial => "canvas") %>");
  $('#slide_menu').html("<%= escape_javascript render(:partial => "slide_menu") %>");
  
  $('#current_slide_id').val(<%= @selected_slide.id %>);
  StoryBoard.get_slide(<%= @selected_slide.id %>);
  
  $('#transition_link').click(function(){
    $('#transition form').toggle();
    return false;
  });
  
  $('#remove_transition').click(function(){
    $('#slide_transfer_to_slide_id').val(null);
    $('#slide_transfer_wait').val(null);
    $(this).closest('form').submit();
    return false;
  });

  $('#transition_slide_selector').click(function(){
    transition_slide_selecting = true;
    return false;
  });
  
  $('#add_slide_form a').click(function(){
    $('#add_slide_form').submit();
    return false;
  });
  
  $('#share_link').click(function(){
    $('#share_url').toggle();
    return false;
  });
  
  $('#preview_slide_form a').click(function(){
    $('#preview_slide_form #current_slide_id').val($("#canvas").data("slide_id"));
    $('#preview_slide_form').submit();
    return false;
  });
  
  StoryBoard.setup_slide_right_click_menu();
  StoryBoard.setup_sortable_sidebar();
  StoryBoard.setup_jcrop();
<% end %>

app/views/story_boards/update.js.erb
$('span#security_level a').text('<%= @story_board.security_level_desc %>');
$('#story_board_security_dialog').dialog('close');
$('#selected-slide').html("<%= escape_javascript render(:partial => "canvas") %>");
StoryBoard.get_slide(<%= @selected_slide.id %>);