config/routes.rb
RailsSample::Application.routes.draw do
  resources :slides, :only => [:show]
  resources :action_items, :only => [:create, :update, :destroy]
  resources :users do
    member do
      put :change_password_update
    end
  end
  
  resources :story_boards
  resources :story_boards do
    resources :slides do
      post :resize
      post :crop
    end
    member do
      get :preview
      get :duplicate
    end
  end
  resources :story_board_attachments, :only => [:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_prospects

  root :to => "home#index"
  
  match '/signup',  :to => 'users#new', :as => :sign_up
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/change_password', :to => 'users#change_password', :as => :change_password

  match 'ajax/editable' => 'ajax#editable'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation, :admin
  has_secure_password
  
  validates_presence_of :password, :on => :create

  validates :username, :presence => true, :uniqueness => true, :format => { :with => /^[a-z0-9\-_]+$/i,
      :message => "Invalid character in username" }
  validates :email, :presence => true, :uniqueness => true, :email => true
  
  has_many :story_boards
  
  def next_story_board_title
    untitled_story_boards = story_boards.where(:title => StoryBoard::DEFAULT_TITLE)
    untitled_story_boards.size == 0 ? StoryBoard::DEFAULT_TITLE : untitled_story_boards.first.get_next_duplicate_title
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :must_be_admin, :only => [:index, :new]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, :notice => "User #{@user.username} successfully created." }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
  
  def change_password_update
    if current_user.authenticate(params[:old_password])
      if ((params[:password] == params[:password_confirmation]) && !params[:password_confirmation].blank?)
          current_user.password_confirmation = params[:password_confirmation]
          current_user.password = params[:password]
        
          if current_user.save!
              flash[:notice] = "Password successfully updated"
              redirect_to current_user
          else
              flash[:alert] = "Password not changed"
              render :action => 'change_password'
          end
         
      else
          flash[:alert] = "New Password mismatch" 
          render :action => 'change_password'
      end
    else
      flash[:alert] = "Old password incorrect" 
      render :action => 'change_password'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
- if @user.errors.any?
  #error_explanation
    %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

= form_for @user do |f|
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :email
    = f.text_field :email    
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation, "Confirmation"
    = f.password_field :password_confirmation
  .actions
    = f.submit

app/views/users/change_password.html.haml
%h1 Change Password

= form_tag change_password_update_user_path(current_user), :method => :put do
  .field
    = label_tag 'Old password'
    = password_field_tag 'old_password', nil, :size => 45, :class => 'text'
    
  .field
    = label_tag 'New password'
    = password_field_tag 'password', nil, :size => 45, :class => 'text'
    .help Between 4 and 40 characters

  .field
    = label_tag 'Confirm new password'
    = password_field_tag 'password_confirmation', nil, :size => 45, :class => 'text'
        
  = submit_tag 'Change password'

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Encrypted password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.encrypted_password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.haml
- if current_user.admin?
  %h1 New user

  = render 'form'

  = link_to 'Back', users_path

app/views/users/show.html.haml
%h1 My Account

%p 
  Username:
  = @user.username
%p
  Email:
  = @user.email
  
= link_to 'Change password', change_password_path