config/routes.rb
RailsSample::Application.routes.draw do
  resources :slides, :only => [:show]
  resources :action_items, :only => [:create, :update, :destroy]
  resources :users do
    member do
      put :change_password_update
    end
  end
  
  resources :story_boards
  resources :story_boards do
    resources :slides do
      post :resize
      post :crop
    end
    member do
      get :preview
      get :duplicate
    end
  end
  resources :story_board_attachments, :only => [:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_prospects

  root :to => "home#index"
  
  match '/signup',  :to => 'users#new', :as => :sign_up
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/change_password', :to => 'users#change_password', :as => :change_password

  match 'ajax/editable' => 'ajax#editable'
  

end

app/models/shared/attachment_helper.rb
module Shared
  module AttachmentHelper

    class << self
      def included(base)
        base.extend ClassMethods
      end
    end

    module ClassMethods
      def has_attachment(name, options = {})

        if Rails.env == 'test'
          # store images locally
          options[:path]  = ":rails_root/public/#{Rails.env}#{options[:path]}"
          options[:url]   = "#{Rails.env}#{options[:path]}"
        else
          options[:storage]         = :s3
          options[:s3_credentials]  = File.join(Rails.root, 'config', 's3.yml')          
        end

        # pass things off to paperclip.
        has_attached_file name, options
      end
    end
  end
end

app/models/shared/slide_creator.rb
module Shared
  module SlideCreator

    def create_slides(starting_order_number=0)
    end
    
    def update_slide(slide,attachment)
    end
    
    def refresh_slide_order_numbers
    end
  end
end

app/views/shared/_file_upload_templates.erb
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td>
                <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>
            </td>
            <td class="start">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-primary">
                    <i class="icon-upload icon-white"></i>
                    <span>{%=locale.fileupload.start%}</span>
                </button>
            {% } %}</td>
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-warning">
                <i class="icon-ban-circle icon-white"></i>
                <span>{%=locale.fileupload.cancel%}</span>
            </button>
        {% } %}</td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
            <td class="preview">{% if (file.thumbnail_url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete">

        </td>
    </tr>
{% } %}
</script>

app/views/shared/_footer.html.haml
#site-footer.ui-layout-south
  #site-bottom-nav
    %span
      = link_to "About Us", "javascript:void(0);"
    |
    %span
      = link_to "Contact Us", "javascript:void(0);"
    |
    %span
      = link_to "Privacy", "javascript:void(0);"
    |
    %span
      = link_to "Terms", "javascript:void(0);"
    |
    %span
      = link_to "FAQ", "javascript:void(0);"
    |
    %span
      = link_to "Blog", "javascript:void(0);"

app/views/shared/_header.html.haml
#site-header.ui-layout-north
  #site-logo
    Rails Sample
    - unless Rails.env == 'production'
      %strong= "** #{Rails.env} **"
  #site-top-nav
    - if user_signed_in?
      = render "shared/user_header"
    - else
      = render "shared/guest_header"

app/views/shared/_plupload.js.erb
<% session_key_name = Rails.application.config.session_options[:key] %>
jQuery(document).ready(function() {
  $("#uploader").pluploadQueue({
    runtimes: 'html5,flash,silverlight',
    url: '<%= story_board_attachments_path %>',
    max_file_size: '10mb',
    multiple_queues: true,
    flash_swf_url: "/javascripts/plupload/plupload.flash.swf",  
    silverlight_xap_url: "/javascripts/plupload/plupload.silverlight.xap",
    multipart: true,
    multipart_params: {
      '_http_accept': 'application/javascript',
      'authenticity_token' : '<%= form_authenticity_token %>',
      '<%= session_key_name %>' : encodeURIComponent('<%= u cookies[session_key_name] %>'),
      'story_board_id': '<%= @story_board.id %>'
    },
    filters: [
      {title: "Images", extensions: "jpg,jpeg,png,pdf,gif"}
    ],
    init: {
      FileUploaded: function(up, file, info) {
        eval(info["response"]);
      }
    }
  });
});

app/views/shared/_sign_in_form.html.haml
#sign-in
  = form_tag sessions_path do
    .field
      = label_tag :email
      = text_field_tag :email    
    .field
      = label_tag :password
      = password_field_tag :password
    .actions
      = submit_tag "Sign in"

app/views/shared/_sign_up_form.html.haml
#sign-up
  = form_for User.new do |f|
    .field
      = f.label :username
      = f.text_field :username
    .field
      = f.label :email
      = f.text_field :email    
    .field
      = f.label :password
      = f.password_field :password
    .field
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation
    .actions
      = f.submit "Sign up"

app/views/shared/_user_header.html.haml
-# %span.user_header
  -# %p.username= current_user.username
  -# = link_to 'Logout', signout_path, :method => :delete
  -# = link_to 'My Storyboards', story_boards_path
  -# = link_to 'Account', current_user
  -# - if current_user.admin?
    -# = link_to 'Admin: Add new user', sign_up_path, :class => 'admin_task'
    
%span 
  Welcome 
  %strong= current_user.username
|
%span
  = link_to "My Storyboards", story_boards_path
|
%span
  = link_to "My Account", current_user
|
%span
  = link_to "Logout", signout_path, :method => :delete
- if current_user.admin?
  |
  %span
    = link_to 'Admin: Add new user', sign_up_path, :class => 'admin_task'