config/routes.rb
RailsSample::Application.routes.draw do
  resources :slides, :only => [:show]
  resources :action_items, :only => [:create, :update, :destroy]
  resources :users do
    member do
      put :change_password_update
    end
  end
  
  resources :story_boards
  resources :story_boards do
    resources :slides do
      post :resize
      post :crop
    end
    member do
      get :preview
      get :duplicate
    end
  end
  resources :story_board_attachments, :only => [:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_prospects

  root :to => "home#index"
  
  match '/signup',  :to => 'users#new', :as => :sign_up
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/change_password', :to => 'users#change_password', :as => :change_password

  match 'ajax/editable' => 'ajax#editable'
  

end

app/models/action_item.rb
class ActionItem < ActiveRecord::Base
  include Shared::AttachmentHelper
  
  belongs_to :slide
  serialize :data
  validates_presence_of :width, :height, :top, :left, :slide_id
  validates_presence_of :slide_id, :action_type, :if => proc{ |action_item| !action_item.data.nil? }
  delegate :story_board, :to => :slide
  
  has_attachment :user_gif, { :path => "/story_boards/:story_board_id/slides/:slide_id/action_items/:id/:style.:extension" }
  
  scope :links, where(:action_type => 'link')
  scope :order_by_top, order('action_items.top, action_items.left')

  FONTS = [
    ['Arial/Helvetica', 'Arial, Helvetica, sans-serif'],
    ['Times New Roman/Times', '"Times New Roman", Times, serif'],
    ['Courier New/Courier', '"Courier New", Courier, monospace'],
    ['Verdana', 'Verdana, Geneva, sans-serif']
  ]
  
  FONT_COLORS = [
    "FFFFFF","FFDFDF","FFBFBF","FF9F9F","FF7F7F","FF5F5F","FF3F3F","FF1F1F","FF0000","DF1F00",
    "C33B00","A75700","8B7300","6F8F00","53AB00","37C700","1BE300","00FF00","00DF1F","00C33B",
    "00A757","008B73","006F8F","0053AB","0037C7","001BE3","0000FF","0000df","0000c3","0000a7",
    "00008b","00006f","000053","000037","00001b","000000" 
  ]
  
  BACKGROUND_COLORS = FONT_COLORS << 'transparent'

  def data_attrs
    data = attributes.dup
    %w{data id slide_id created_at updated_at}.each{|key| data.delete(key)}
    (self.data || {}).each do |key, val|
      data["data_#{key}"] = val
    end
    data
  end
  
  def duplicate(slide)
    if self.action_type
      action_item = ActionItem.create(:slide => slide, :action_type => self.action_type, :top => self.top, 
                                      :left => self.left, :width => self.width, :height => self.height, :data => self.data)
      action_item.update_attributes :user_gif => self.user_gif if self.user_gif.present?
    end
  end
  
  def remove_internal_link
    self.data["internal_link"] = ""
    self.save
  end
  
  
  def incomplete?
    case
    when action_type == 'link' then data.nil? ? true : data['internal_link'].blank?
    else false
    end
  end
  
  def as_json(options = { })
      h = super(options)
      h[:incomplete] = incomplete?
      h
  end
  
end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  def create
    @action_item = ActionItem.new(params[:action_item])

    if @action_item.save
      render :json => { :action_item => @action_item }, :status => :created
    else
      render :json => @action_item.errors, :status => :unprocessable_entity
    end
  end

  def update
    
    @action_item = ActionItem.find(params[:action_item_id])
    attributes = params[:action_item]

    if @action_item.action_type == 'link' && params[:action_item][:data].present?
      if params[:action_item][:data][:internal_link] == 'external'
        attributes[:data][:link_type] = 'external'
        attributes[:data][:internal_link] = ''
      else
        attributes[:data][:link_type] = 'internal'
        attributes[:data][:external_link] = ''
      end
    end

    respond_to do |format|
      if @action_item.update_attributes(attributes)
        format.json { render :json => @action_item.to_json }
        format.js
      else
        format.json  { render :json => @action_item.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @action_item = ActionItem.find(params[:id])
    @action_item.destroy
    render :json => {}, :status => :ok
  end

end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/views/action_items/_actions.html.haml
.actions
  = button_tag "Done", :class => 'action_item_done'

app/views/action_items/_checkbox.html.haml
#checkbox_action_item
  = form_tag action_item_path, :method => 'put', :remote => true do 
    = hidden_field_tag :action_item_id

    %div.action_options.checkbox_view
      = label_tag "Checkmark to use:"
      %ul
        %li
          = radio_button_tag "action_item[data[checkbox_type]]", "check_mark", true, :class => 'checkbox'
          %div.check_box_choice= image_tag 'check_mark.png'
        %li
          = radio_button_tag "action_item[data[checkbox_type]]", "x_mark", false, :class => 'checkbox'
          %div.check_box_choice= image_tag 'x_mark.png'
      .clear
      = label_tag 'Default checked'
      = check_box_tag "action_item[data[checked]]", true
      .clear
      
    = render 'action_items/actions'

app/views/action_items/_gif.html.haml
#gif_action_item
  = form_tag action_item_path, :method => 'put', :remote => true, :multipart => true do 
    = hidden_field_tag :action_item_id

    %div#gifs.action_options
      %p Select animated gif
      - (1..4).each do |num|
        .field
          = radio_button nil, "action_item[data[gif_image]]", "ajax-loader-#{num}"
          = image_tag("ajax-loader-#{num}.gif")
      .field
        = radio_button nil, "action_item[data[gif_image]]", ""
        = label_tag "Choose my own image"
      .field
        .image
        = link_to image_tag('delete.gif'), '#', :class => 'delete_image'
        = file_field :action_item, :user_gif, :accept => 'image/png,image/gif,image/jpeg'
        
    = render 'action_items/actions'

app/views/action_items/_link.html.haml
#link_action_item          
  = form_tag action_item_path, :method => 'put', :remote => true do 
    %div#actions
      = hidden_field_tag :action_item_id
      = hidden_field_tag 'action_item[data[link_type]]'
      
      %div.action_options.link_view
        .field
          %span Link to:           
          - slides = []
          - slides << ["Choose a screen",""]
          - @story_board.slides.each_with_index{|s,i| slides << ["#{i+1}. #{s.original_filename}", s.id]}
          - slides << ["External Web Page", "external"]
          = select_tag "action_item[data[internal_link]]", options_for_select(slides), :include_blank => false
          
        %ul.external_link_fields.hide
          %li
            %span Web page:
            = text_field_tag "action_item[data[external_link]]"
        
        %ul
          %li
            = check_box_tag 'action_item[data[maintain_scroll]]'
            %span Keep Scroll Position
      
      = render 'action_items/actions'
          

app/views/action_items/_radio.html.haml
#radio_action_item
  = form_tag action_item_path, :method => 'put', :remote => true do 
    = hidden_field_tag :action_item_id

    %div.action_options.radio_view
      = label_tag 'Default selected'
      = check_box_tag "action_item[data[selected]]", true
    
    = render 'action_items/actions'

app/views/action_items/_text.html.haml
#text_action_item           
  = form_tag action_item_path, :method => 'put', :remote => true, :class => 'action_item_form' do 
    %div#actions
      = hidden_field_tag :action_item_id

      %div.action_options.text_view
        %ul
          %li
            = radio_button_tag "action_item[data[text_box_lines]]", "single", true, :class => 'text_lines'
            %span Single line
          %li
            = radio_button_tag "action_item[data[text_box_lines]]", "multiple", false, :class => 'text_lines'
            %span Multiple lines
        .field
          = label_tag 'Font type'
          = select nil, "action_item[data[font_type]]", ActionItem::FONTS, {}, {:class => 'font-type'}
        .field
          = select nil, "action_item[data[font_color]]", options_for_select(ActionItem::FONT_COLORS,'000000'), {}, {:class => 'font-colorpicker'}
        .field
          = label_tag 'Font size'
          = select nil, "action_item[data[font_size]]", options_for_select((5..20).each{|x| ['%dpt' % x, x]},"14"), {}, {:class => 'font-size'}
        .field
          = select nil, "action_item[data[background_color]]", options_for_select(ActionItem::BACKGROUND_COLORS, 'transparent'), {}, {:class => 'background-colorpicker'}
        .field
          = label_tag 'Variable name'
          = text_field_tag "action_item[data[save_variable]]", nil, {:onkeypress => 'return View.validateVariableName(event)'}
      
      = render 'action_items/actions'

app/views/action_items/_variable.html.haml
#variable_action_item
  = form_tag action_item_path, :method => 'put', :remote => true do 
    = hidden_field_tag :action_item_id

    %div.action_options.variable_view
      .field
        = label_tag 'Variable name'
        = select nil,  "action_item[data[insert_variable]]", options_for_select(@story_board.variables), {}, {:class => 'insert-variable'}
      .field
        = label_tag 'Font type'
        = select nil, "action_item[data[var_font_type]]", ActionItem::FONTS, {}, {:class => 'var-font-type'}
      .field
        = select nil, "action_item[data[var_font_color]]", options_for_select(ActionItem::FONT_COLORS,'000000'), {}, {:class => 'var-font-colorpicker'}
      .field
        = label_tag 'Font size'
        = select nil, "action_item[data[var_font_size]]", options_for_select((5..20).each{|x| ['%dpt' % x, x]},"14"), {}, {:class => 'var-font-size'}
    
    = render 'action_items/actions'